<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php  echo $block->getGridHtml(); ?>
<input type="hidden" name="category_products_plan" id="in_category_products_plan" data-form-part="warranty_index_edit" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "Clyde_Warranty/catalog/category/assign-plan": {
                "selectedProducts": <?php /* @escapeNotVerified */ echo $block->getProductsJson(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
    require([
    'jquery',
    'accordion'
], function ($) {
    'use strict';
    $( document ).ready(function() {                      
        $( "#assign_products_plan" ).accordion({
            "openedState": "active",
            "collapsible": true,
            "active": [1,4], /** Integrat Dynamic open tab  */
            "multipleCollapsible": true,
        });
    });                 
});
</script>