<!--div class="small-promo">
	<div class="small-promo-content"> 
	  <span class="small-promo-text-desktop">Speak to an expert today!</span>
	  <h4 class="small-promo-heading">&nbsp;1 (646)  921-1112</h4>
	</div>
</div-->
<?php echo $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('speak_to_expert')
          ->toHtml(); ?>
<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeID       = $storeManager->getStore()->getStoreId(); 
if($storeID==2){
	echo '<link  rel="stylesheet" type="text/css"  media="all" href="'.$this->getViewFileUrl('css/bakery.css').'" />';
}