<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseUrl = $storeManager->getStore()->getBaseUrl();
	$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<div class="announcement-bar">
	<div class="cont-left">
		<!--p align="left">✔  <i> Free Shipping </i>
		 &nbsp;&nbsp; 
		✔ <i> Easy Returns </i>  &nbsp;&nbsp; ✔ <i> Price Match Guarantee  </i> </p-->
		<?php echo $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('top_left_announcement')
          ->toHtml(); ?>
	</div>
	<div class="cont-right">
		<ul>
			<li><a href="<?php echo $baseUrl; ?>about-us">About Us</a></li>
			<li>
				<a href="<?php echo $baseUrl; ?>customer-service">Customer Service
					<span class="arrowdown">
						<svg aria-hidden="true" focusable="false" role="presentation" xmlns="http://www.w3.org/2000/svg" width="8" height="6" viewBox="0 0 8 6">
						  <g fill="currentColor" fill-rule="evenodd">
							<polygon class="icon-chevron-down-left" points="4 5.371 7.668 1.606 6.665 .629 4 3.365"/>
							<polygon class="icon-chevron-down-right" points="4 3.365 1.335 .629 1.335 .629 .332 1.606 4 5.371"/>
						  </g>
						</svg>
					</span>
				</a>
				<div class="dropdown-content">
					<?php echo $this->getLayout()
					  ->createBlock('Magento\Cms\Block\Block')
					  ->setBlockId('customer_service_links')
					  ->toHtml(); ?>
					<!--ul class="dropdown-contentul">
						<li><a href="<?php echo $baseUrl; ?>contact">Contact Us</a></li>
						<li><a href="<?php echo $baseUrl; ?>guarantee">Price Match Guarantee</a></li>
						<li><a href="<?php echo $baseUrl; ?>shipping-policy">Shipping policy</a></li>
					</ul-->
				</div>
			</li>
			<li>
				<a href="<?php echo $baseUrl; ?>customer/account">My Account
					<span class="arrowdown">
						<svg aria-hidden="true" focusable="false" role="presentation" xmlns="http://www.w3.org/2000/svg" width="8" height="6" viewBox="0 0 8 6">
						  <g fill="currentColor" fill-rule="evenodd">
							<polygon class="icon-chevron-down-left" points="4 5.371 7.668 1.606 6.665 .629 4 3.365"/>
							<polygon class="icon-chevron-down-right" points="4 3.365 1.335 .629 1.335 .629 .332 1.606 4 5.371"/>
						  </g>
						</svg>
					</span>
				</a>
				<div class="dropdown-content dropdown-mincontent">
				<ul class="dropdown-contentul">
					<?php if($customerSession->isLoggedIn()) { ?>
						<li><a href="<?php echo $baseUrl; ?>customer/account">My Account</a></li>
						<li><a href="<?php echo $baseUrl; ?>customer/account/logout">Logout</a></li>
					<?php }else{ ?>
						<li><a href="<?php echo $baseUrl; ?>customer/account/login">Login</a></li>
						<li><a href="<?php echo $baseUrl; ?>customer/account/create">Register</a></li>
					<?php } ?>
				</ul>
				</div>
			</li>
		</ul>
	</div>
	<div class="clearfix">
	</div>
</div>