<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$product = $this->getProduct();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img alt="main product photo" class="gallery-placeholder__image" src="<?= /* @noEscape */ $mainImageData ?>" />
</div>

<div class="certification-block">
    <?php /*$attri = $product->getResource()->getAttribute('certifications')->getFrontend()->getValue($product);
        $data = explode(', ', $attri);
        foreach ($data as $value) {
            if($value == 'NSF'){
                echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('nsf-listed')->toHtml();
            } elseif ($value == 'Intertek') {
                echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('intertek')->toHtml();
            }
        } */
    ?>
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>
            }
        }
    }
</script>